### ISSUE TITLE
Cheat sheet is 404

### ISSUE THREAD

**Issue by Miha-x64** [passy/awesome-recursion-schemes#18]
> The Hitchhiker's Guide to Morphisms - Overview of different morphisms including a printable PDF.

GitHub gives error 404 on this page now.

**Comment by passy** [comment]
Thanks! Asked about it here: https://twitter.com/__protected/status/701543460088762368

**Comment by MasseR** [comment]
I'm not the official source for the blog, but I have a copy of the cheatsheet. Is it ok for me to share the link for it?

**Comment by passy** [comment]
@MasseR I think so? Would definitely like to have a working link for it again. :)

**Comment by MasseR** [comment]
https://github.com/passy/awesome-recursion-schemes/pull/19
